import React from 'react'

export default function Terms() {
  return (<>
    <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eu non diam phasellus vestibulum lorem sed. Sed enim ut sem viverra aliquet eget sit amet. Etiam non quam lacus suspendisse faucibus interdum posuere lorem. Arcu dui vivamus arcu felis bibendum ut. Elit pellentesque habitant morbi tristique senectus et. Nec sagittis aliquam malesuada bibendum arcu vitae. Viverra tellus in hac habitasse platea dictumst vestibulum rhoncus. Odio tempor orci dapibus ultrices in. Cursus eget nunc scelerisque viverra mauris in.

    Ut tristique et egestas quis ipsum suspendisse. Quis viverra nibh cras pulvinar mattis. Tortor dignissim convallis aenean et tortor. Quis vel eros donec ac odio tempor orci dapibus ultrices. Lacus luctus accumsan tortor posuere ac ut consequat semper viverra. Nulla malesuada pellentesque elit eget gravida cum sociis natoque. Faucibus turpis in eu mi bibendum neque egestas. At risus viverra adipiscing at in tellus integer feugiat. Egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Aliquet porttitor lacus luctus accumsan tortor posuere.
    
    Et sollicitudin ac orci phasellus. At tempor commodo ullamcorper a lacus vestibulum sed arcu. Vulputate ut pharetra sit amet aliquam id diam maecenas. Sed odio morbi quis commodo odio aenean sed adipiscing. Mauris cursus mattis molestie a iaculis at erat pellentesque. Nisl pretium fusce id velit ut tortor pretium. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim. Natoque penatibus et magnis dis. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum odio.
    
    Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Ridiculus mus mauris vitae ultricies. Enim diam vulputate ut pharetra. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel. Vitae ultricies leo integer malesuada nunc vel risus. Diam quis enim lobortis scelerisque fermentum dui. Ultrices sagittis orci a scelerisque purus semper eget duis. Faucibus a pellentesque sit amet porttitor eget. Tempor commodo ullamcorper a lacus vestibulum sed arcu non odio. Non odio euismod lacinia at. Aenean vel elit scelerisque mauris pellentesque pulvinar. Parturient montes nascetur ridiculus mus mauris vitae ultricies leo integer. Tincidunt eget nullam non nisi est sit amet. Neque laoreet suspendisse interdum consectetur libero id faucibus. Eu lobortis elementum nibh tellus molestie nunc non blandit.
    
    Praesent elementum facilisis leo vel fringilla est ullamcorper eget nulla. Enim ut sem viverra aliquet eget sit amet tellus. Cras pulvinar mattis nunc sed blandit libero volutpat sed. Urna molestie at elementum eu facilisis. Amet est placerat in egestas erat imperdiet sed euismod. Consequat nisl vel pretium lectus quam id leo in. Amet cursus sit amet dictum sit amet justo. Orci dapibus ultrices in iaculis nunc sed augue lacus viverra. Sed velit dignissim sodales ut. Maecenas pharetra convallis posuere morbi leo urna.</div>
    </>)
}
